# Generated by Django 5.0 on 2023-12-14 14:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Team',
                'db_table': 'teams',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('home_score', models.IntegerField(blank=True, default=0, null=True)),
                ('away_score', models.IntegerField(blank=True, default=0, null=True)),
                ('away', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='away_tournament', to='league.teams')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='home_tournament', to='league.teams')),
            ],
            options={
                'verbose_name': 'Tournaments',
                'verbose_name_plural': 'Tournaments',
                'db_table': 'tournaments',
                'ordering': ['home'],
            },
        ),
    ]
